#!/bin/bash
sudo apt install wget
MANIFEST=git://github.com/LineageOS/android.git
BRANCH=lineage-17.1  ##edit this

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice.Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name "dodyirawan85"
git config --global user.email 40514988+dodyirawan85@users.noreply.github.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

pwd
ls

##delete these lines, and replace with your own lines of device sauce
git clone https://github.com/Andromax-Devices/android_device_haier_g151.git device/haier/g151 --depth=1
git clone https://github.com/Andromax-Devices/android_device_cyanogen_msm8909-common.git device/cyanogen/msm8909-common --depth=1
git clone https://github.com/Andromax-Devices/android_kernel_cyanogen_msm89xx.git kernel/cyanogen/msm89xx --depth=1
git clone https://github.com/Andromax-Devices/proprietary_vendor_haier.git vendor/haier --depth=1

cd /tmp/rom
